import './globals.css'
import { Expletus_Sans } from 'next/font/google';

const expletus_Sans= Expletus_Sans({
  subsets: ['latin'],
  display: 'swap'
})

export const metadata = {
  title: 'Pranjul Agrawal',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={expletus_Sans.className}>
      <body className='mb-10'>{children}</body>
    </html>
  )
}
